### ISSUE TITLE
Is there a runtime limit? 

### ISSUE THREAD

**Issue by cheng-hsiang-chiu** [tsung-wei-huang/ece556#4]
Is there a runtime limit for this assignment as the last one?

**Comment by tsung-wei-huang** [comment]
Let's still target 5 mins - can your program finish in 5 mins? If not, we can target 10 mins.

**Comment by cheng-hsiang-chiu** [comment]
Yes, my program can finish in 5 minutes.

**Comment by tsung-wei-huang** [comment]
Okay, let's do 5 mins then.
